### ISSUE TITLE
sbt using java 8

### ISSUE THREAD

**Issue by andybryant** [leigh-perry/nix-setup#5]
I noticed that sbt seems to be using java 8 despite the nix scala script seeming to force it to use java 11. will try and look into this later today.

This causes issues when attempting to use `Runtime.version()` in build script which is Java9+

```
./sn scala
sbt
sbt:nix-setup> eval System.getProperty("java.version")
[info] ans: String = 1.8.0_202
sbt:nix-setup> eval System.getProperty("java.home")
[info] ans: String = /nix/store/xycgjy1l3j3980wclvb5m4l2ddh33pp6-zulu1.8.0_202-8.36.0.1/jre
```

**Comment by leigh-perry** [comment]
A fix in Nix would be great. In the meantime, I have hacked around it with an alias for `sbt` which does:
```sbt -java-home $JAVA_HOME "$@"```

**Comment by andybryant** [comment]
good to know 👍

**Comment by forficate** [comment]
The issue is `scala.nix` defines a `local` variable called `pkgs` which overrides the jre but the local variable defined is never used.

```

let
  use-jdk = jdk11;   # callPackage jdk/shared-jdk.nix { inherit jdk-name; inherit jdk-sha; };
  pkgs = import <nixpkgs> { overlays = [ (self: super: {
    jdk = use-jdk;
    jre = use-jdk;
  }) ]; }; 
  # cfg = (import jdk/jdk11.nix);
  # jdk-name = cfg.jdk-name;
  # jdk-sha = cfg.jdk-sha;
in
...
buildInputs = [
  sbt
  ...
]
```

The `sbt` value in the buildInputs stage comes from the below scope, `with` changes the scoping see "with statement" at https://nixos.wiki/wiki/Nix_Expression_Language.
```
with import (builtins.fetchTarball {
  # Descriptive name to make the store path easier to identify
  name = "nixos-unstable-2020-02-02";
  # Commit hash for nixos-unstable as of 2020-02-02 - get from head (git log)
  url = https://github.com/nixos/nixpkgs/archive/4928d8ca89261d4fbd1811324e402a6025c77574.tar.gz;
  # Hash obtained using `nix-prefetch-url --unpack <url>`
  sha256 = "12r432bp0lszczrdcliqfa32qa70fbv0fdq74fw55q0mibn9sg68";
}) {};
```

To do what you want it to do you would need `buildInputs = [ pkgs.sbt ]` which is the shadowed variable overridden.

This gives the below:
```
sbt:nix-setup> eval System.getProperty("java.version")
[info] ans: String = 11.0.1
```

You should also prefix every over package in `buildInputs` to use the `pkgs.*` variable so they are the same package set.

The original idea of updating it globally was a good one, which can be done as:

```
with import (builtins.fetchTarball {
  # Descriptive name to make the store path easier to identify
  name = "nixos-unstable-2020-02-02";
  # Commit hash for nixos-unstable as of 2020-02-02 - get from head (git log)
  url = https://github.com/nixos/nixpkgs/archive/4928d8ca89261d4fbd1811324e402a6025c77574.tar.gz;
  # Hash obtained using `nix-prefetch-url --unpack <url>`
  sha256 = "12r432bp0lszczrdcliqfa32qa70fbv0fdq74fw55q0mibn9sg68";
}) {
  config = {
    packageOverrides = pkgs: {
      jdk = pkgs.jdk11;
      jre = pkgs.jdk11;
    };
  };
};
```

Then all you need is `buildInputs = [sbt]` again.

It's good to remember everything is an expression. The `import` is bringing in a function to generate the package set which was previously applied with `{}`. The updated applies it with the `config` value set with our `packageOverrides`, `packageOverrides` is roughly `pkgs => pkgs`.

**Comment by lpfoxtel** [comment]
@forficate 
Hey Adam, I missed your comment when you first posted it... thanks for the tip!

**Comment by leigh-perry** [comment]
@forficate 
Hey Adam, I missed your comment when you first posted it..... thanks for the tip!

**Comment by leigh-perry** [comment]
Fixed thanks to @forficate
